export { default as Home } from "./Home";
export { default as Cart } from "./Cart";
export { default as Products } from "./Products";
export { default as About } from "./About";
export { default as SingleProduct } from "./SingleProduct";
export { default as PrivacyPolicy } from "./PrivacyPolicy";
export { default as TermsOfService } from "./TermsOfService";
export { default as PageNotFound } from "./PageNotFound";
export { default as ContactUs } from "./ContactUs";
